modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="betamod_alpha"
version="1.0.0"
displayName="Betamod alpha"
credits="Created using mod maker MCreator"
displayURL="https://gitlab.com/betawolfy/wolfymod"
authors="betawolfy"
description='''
Version alpha du mod Wolfycraft
'''

[[dependencies.betamod_alpha]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




